server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language:
        # First language is the default language
        - en-US
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: INFO
    #logfile: pygeoapi.log

metadata:
    identification:
        title:  Pixxel API for Country Spatial Data.
        description: Provides an API to county geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://www.pixxel.space/
    license:
        name: Awesome license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Pixxel
        url: https://www.pixxel.space/
    contact:
        name: Pixxel
        city: Bangalore
        stateorprovince: Karnataka
        postalcode: 560038
        country: India
        email: admin@pixxel.co.in

resources:
    countries:
        type: collection
        title: Countries
        description: Countries of the world, public domain
        keywords: countries
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            # - type: feature
            #   name: GeoJSON
            #   data: ../countries/data/archive/countries.geojson
            #   id_field: id
            #   title_field: admin
            - type: feature
              name: PostgreSQL
              data:
                host: db
                port: 5432
                dbname: pixxel
                user: postgres
                password: wDnfWovh4uf3
                search_path: ['public']
              id_field: id
              table: countries
              title_field: name
              geom_field: geometry
